LOCATIONS = [
    {
        "id": "dorm",
        "name": "宿舍区",
        "type": "residence",
        "description": "新生最熟悉的起点，晚上适合休息和反思。",
        "x": 120,
        "y": 180,
        "available_actions": ["move", "rest", "talk"],
        "event_tags": ["rest", "social"],
    },
    {
        "id": "teaching_building",
        "name": "教学楼",
        "type": "academic",
        "description": "课程、迟到、问路和同班交流最常发生的地方。",
        "x": 380,
        "y": 130,
        "available_actions": ["move", "attend_class", "talk", "ask_help"],
        "event_tags": ["class", "lost", "social"],
    },
    {
        "id": "canteen",
        "name": "食堂",
        "type": "dining",
        "description": "饭点人流密集，容易发生拼桌、排队和偶遇。",
        "x": 300,
        "y": 310,
        "available_actions": ["move", "eat", "talk"],
        "event_tags": ["meal", "social"],
    },
    {
        "id": "library",
        "name": "图书馆",
        "type": "study",
        "description": "适合学习、安静反思，也可能发生失物招领事件。",
        "x": 560,
        "y": 250,
        "available_actions": ["move", "study", "talk", "handle_lost_item"],
        "event_tags": ["study", "lost_item"],
    },
    {
        "id": "stadium",
        "name": "体育场",
        "type": "sports",
        "description": "运动、社团活动和偶遇发生地。",
        "x": 170,
        "y": 430,
        "available_actions": ["move", "rest", "talk"],
        "event_tags": ["sports", "social"],
    },
    {
        "id": "club_fair",
        "name": "社团招新点",
        "type": "club",
        "description": "新生认识学长学姐、寻找归属感的关键地点。",
        "x": 520,
        "y": 420,
        "available_actions": ["move", "join_activity", "talk"],
        "event_tags": ["club", "social"],
    },
    {
        "id": "lost_and_found",
        "name": "失物招领处",
        "type": "service",
        "description": "校园卡、水杯和教材失而复得的地点。",
        "x": 650,
        "y": 350,
        "available_actions": ["move", "handle_lost_item", "talk"],
        "event_tags": ["lost_item", "service"],
    },
    {
        "id": "gate",
        "name": "校门 / 商业街",
        "type": "gate",
        "description": "校园边界和生活服务区域。",
        "x": 80,
        "y": 340,
        "available_actions": ["move", "talk", "rest"],
        "event_tags": ["life", "social"],
    },
]

PATHS = [
    ("dorm", "teaching_building", 20),
    ("dorm", "canteen", 15),
    ("dorm", "stadium", 20),
    ("teaching_building", "canteen", 10),
    ("teaching_building", "library", 10),
    ("canteen", "library", 15),
    ("canteen", "club_fair", 20),
    ("library", "club_fair", 15),
    ("library", "lost_and_found", 10),
    ("stadium", "club_fair", 20),
    ("gate", "dorm", 15),
    ("gate", "canteen", 20),
]

AGENTS = [
    {
        "id": "agent_wang_yinuo",
        "name": "王一诺",
        "role": "新生",
        "major": "软件工程",
        "personality": "有点社恐但责任感强，遇到问题会先自己扛一会儿。",
        "interests": ["编程", "羽毛球", "技术社团"],
        "long_term_goals": ["适应大学生活", "加入技术社团", "认识同专业朋友"],
        "social_style": "慢热，熟悉后话多",
    },
    {
        "id": "agent_chen_nian",
        "name": "陈念",
        "role": "新生",
        "major": "新闻传播",
        "personality": "外向、好奇、喜欢记录校园里的新鲜事。",
        "interests": ["摄影", "校园媒体", "探店"],
        "long_term_goals": ["加入校园媒体", "认识不同专业同学"],
        "social_style": "主动破冰",
    },
    {
        "id": "agent_zhou_lan",
        "name": "周岚",
        "role": "新生",
        "major": "临床医学",
        "personality": "认真谨慎，容易给自己压力，但很可靠。",
        "interests": ["阅读", "志愿服务", "跑步"],
        "long_term_goals": ["保持成绩", "找到稳定学习节奏"],
        "social_style": "礼貌克制",
    },
    {
        "id": "agent_lin_jianchuan",
        "name": "林见川",
        "role": "新生",
        "major": "软件工程",
        "personality": "方向感强，乐于帮忙，但不太主动表达情绪。",
        "interests": ["算法", "篮球", "校园地图"],
        "long_term_goals": ["找到学习伙伴", "参加比赛"],
        "social_style": "实用型社交",
    },
    {
        "id": "agent_li_mengyao",
        "name": "李梦瑶",
        "role": "新生",
        "major": "经济学",
        "personality": "目标明确，喜欢做计划，对社团和机会很敏感。",
        "interests": ["辩论", "商业分析", "社团活动"],
        "long_term_goals": ["锻炼表达能力", "加入有影响力的社团"],
        "social_style": "目标导向",
    },
    {
        "id": "agent_xu_qinghe",
        "name": "徐清和",
        "role": "学长",
        "major": "计算机科学与技术",
        "personality": "温和可靠，熟悉校园和社团流程。",
        "interests": ["开源", "社团管理"],
        "long_term_goals": ["帮助新生融入社团"],
        "social_style": "引导型",
    },
]
